version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
  nest-service:
    image: predictivehire-nest
    container_name: predictivehire-nest-container
    environment:
      MONGO_URL: mongodb:27017
    ports:
      - "3000:3000"

  apollo-service:
    image: predictivehire-apollo
    container_name: predictivehire-apollo-container
    ports:
      - "4000:4000"
    environment:
      NEST_API: http://nest-service:3000


